SpotyApp/Controllers/RadioController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SpotyApp.Services.Interfaces;
using SpotyApp.ViewModels;

namespace SpotyApp.Controllers
{
    public class RadioController : Controller
    {
        private readonly IRadioService _service;

        public RadioController(IRadioService service)
        {
            _service = service;
        }

        /*
         * Synchronous Method
         */
        public IActionResult IndexSync()
        {
            var model = new RadioVM();
            var timer = Stopwatch.StartNew();

            model.Albums = _service.GetTopAlbums(); //Delay 2000ms
            model.Artists = _service.GetTopArtists(); //Delay 2000ms
            model.CurrentNumberOfListeners = _service.GetCurrentNumberOfListeners(); //Delay 1000ms

            timer.Stop();

            ViewBag.Delay = timer.ElapsedMilliseconds; //Sync total delay = 2000ms + 2000ms + 1000ms = 5000ms

            return View(model);
        }


        /*
         * Asynchronous Method but execute syncronous
         */
        public async Task<IActionResult> IndexAsyncA()
        {
            var model = new RadioVM();
            var timer = Stopwatch.StartNew();

            model.Albums = await _service.GetTopAlbumsAsync(); //Delay 2000ms
            model.Artists = await _service.GetTopArtistsAsync(); //Delay 2000ms
            model.CurrentNumberOfListeners = await _service.GetCurrentNumberOfListenersAsync(); //Delay 1000ms

            timer.Stop();

            ViewBag.Delay = timer.ElapsedMilliseconds; //Sync total delay = 2000ms + 2000ms + 1000ms = 5000ms

            return View(model);
        }

        /*
         * Asynchronous Method
         */
        public async Task<IActionResult> IndexAsyncB()
        {
            var model = new RadioVM();
            var timer = Stopwatch.StartNew();

            //Task&async power!
            var albumsPromise =  _service.GetTopAlbumsAsync(); //Delay 2000ms
            var artistPromise = _service.GetTopArtistsAsync(); //Delay 2000ms
            var numberOfListenersPromise = _service.GetCurrentNumberOfListenersAsync(); //Delay 1000ms

            //Get results
            model.Albums = await albumsPromise;
            model.Artists = await artistPromise;
            model.CurrentNumberOfListeners = await numberOfListenersPromise;

            timer.Stop();

            ViewBag.Delay = timer.ElapsedMilliseconds;

            return View(model);
        }
    }
}

SpotyApp/Controllers/SpotyController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SpotyApp.Models;
using SpotyApp.Services.Interfaces;

namespace SpotyApp.Controllers
{
    public class SpotyController : Controller
    {
        private readonly ISpotyService _spotyService;

        public SpotyController(ISpotyService service)
        {
            _spotyService = service;
        }


        public async Task<IActionResult> Index()
        {
            var token = await _spotyService.GetToken();


            /*
             * Get Data Syncronous
             * Details:
             * 1)We are sending a request to Spotify Api and we retrieve new releases for Argentina. We're WAITING for the response.
             * 2)We are sending a request to Spotify Api and we retrieve new releases for Australia. We're WAITING for the response.
             * 3)We are sending a request to Spotify Api and we retrieve new releases for NewZealand. We're WAITING for the response.
             * 4)We are sending a request to Spotify Api and we retrieve new releases for Usa. We're WAITING for the response.
             * 
             * Then, if each request delay 10 seconds, we'd have a total: 40 seconds.
             */

            Stopwatch timerSync = Stopwatch.StartNew();
            var newReleasesArgentina = await _spotyService.GetNewAlbumReleases(token, Countries.ARGENTINA, 50);
            var newReleasesAustralia = await _spotyService.GetNewAlbumReleases(token, Countries.AUSTRALIA, 50);
            var newReleasesNewZealand = await _spotyService.GetNewAlbumReleases(token, Countries.NEW_ZEALAND, 50);
            var newReleasesUsa = await _spotyService.GetNewAlbumReleases(token, Countries.USA, 50);
            timerSync.Stop();

            /*
             * Get Data Asyncronous
             * 
             * Details:
             * For each country, We are sending a request to Spotify Api, generate a Promise. The process is started, but it's NOT BLOCKING, the execution continue
             * 
             * 1) The request start for retrieve Argentina Data and continue.
             * 2) The request start for retrieve Australia Data and continue.
             * 3) The request start for retrieve NewZealand Data and continue.
             * 4) The request start for retrieve Usa Data and continue.
             * 
             * 5) In this point, we have 4 request in PARALLEL --> 4 tasks are executing at same time. --> CONCURRENCY!
             * 
             * 6) When the code meets a "await" STOP the executing until retrieve Argentina Data.
             *    In this moment the process Index() is blocked and the thread is FREE until we have a API response --> EXPLOIT SERVER RESOURCES!
             * 
             * 7) When we have a APi Response, came back to the line:
             * var newReleasesArgentinaResult = await newReleasesArgentinaPromise;
             * And continue!
             * 
             * 8) It's the same for each await Promise.
             * 
             */

            Stopwatch timerAsync = Stopwatch.StartNew();
            var newReleasesArgentinaPromise =  _spotyService.GetNewAlbumReleases(token, Countries.ARGENTINA, 50);
            var newReleasesAustraliaPromise =  _spotyService.GetNewAlbumReleases(token, Countries.AUSTRALIA, 50);
            var newReleasesNewZealandPromise =  _spotyService.GetNewAlbumReleases(token, Countries.NEW_ZEALAND, 50);
            var newReleasesUsaPromise =  _spotyService.GetNewAlbumReleases(token, Countries.USA, 50);

            var newReleasesArgentinaResult = await newReleasesArgentinaPromise;
            var newReleasesAustraliaResult = await newReleasesAustraliaPromise;
            var newReleasesNewZealandResult = await newReleasesNewZealandPromise;
            var newReleasesUsaResult = await newReleasesUsaPromise;

            timerAsync.Stop();


            return View();
        }
    }
}

SpotyApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SpotyApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SpotyApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
 
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Radio App<span class="caret"></span></a>
                        <ul class="dropdown-menu">
                            <li><a asp-area="" asp-controller="Radio" asp-action="IndexSync">With Sync Methods</a></li>
                            <li><a asp-area="" asp-controller="Radio" asp-action="IndexAsyncA">With Async Methods A</a></li>
                            <li><a asp-area="" asp-controller="Radio" asp-action="IndexAsyncB">With Async Methods B</a></li>
                        </ul>
                    </li>
                    <li><a asp-area="" asp-controller="Spoty" asp-action="Index">Spoty App</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - SpotyApp - Powered by <a href="https://fmoralesdev.com/ ">Fran Morales - Dev</a></p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>